# Generated by Django 2.2.dev20181101005010 on 2018-11-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('massage', models.TextField(verbose_name='Message')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Published date')),
            ],
            options={
                'verbose_name': 'thread',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Message')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Published date')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.Thread', verbose_name='thread')),
            ],
            options={
                'verbose_name': 'comment',
            },
        ),
    ]
